### ISSUE TITLE
API URL is incorrect for searchtype='cid' from request() function.

### ISSUE THREAD

**Issue by dncR** [selcukorkmaz/PubChemR#1]
**Source file**: [request.R](https://github.com/selcukorkmaz/PubChemR/blob/master/R/request.R)

**Arguments**

- identifier = c(2244, 3627)
- namespace = 'cid'
- domain = 'compound'
- operation = NULL
- output = 'JSON'
- searchtype = "cid"

**Code**: `request(c(2244, 3627), namespace = 'cid', domain = 'compound', operation = NULL, output = 'JSON', searchtype = "cid")`
**Output**: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/cid/2244,3627/JSON

**Side-effects**: There is a duplicated "cid" component in the returned URL. The correct form should be https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2244,3627/JSON

**Lines raising this problem**
https://github.com/selcukorkmaz/PubChemR/blob/a54b12c1256a56f5238b198b60dafe5d730234cc/R/request.R#L58

The components `namespace` and `searchtype` are set as **cid** in the above code line, which are leading to malformed API URL.

**Comment by selcukorkmaz** [comment]
since namespace = "cid", searchtype cannot be set as "cid".
